import Head from "next/head";
import Image from "next/image";
import Avatar from "../components/Avatar";
import { MicrophoneIcon, ViewGridIcon } from "@heroicons/react/solid";
import { SearchIcon } from "@heroicons/react/outline";
import Footer from "../components/Footer";
import {useRef} from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);

  const search= (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;

    if(!term) return;

    router.push(`/search?term=${term}`);
  };
  return (
    <div className="flex flex-col justify-center h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://www.androidpolice.com/wp-content/uploads/2015/09/nexus2cee_new_google_icon.png"
        />
      </Head>
      <header className="flex w-full p-5 justify-between text-sm text-grey-700">
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>

        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />
          <Avatar url="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBISEhISEhIPEhIYDxkfEhgYDx8SEhAZJSEnJyUhJCQpLjwzKSw4LSQkNDo0ODE1Nzc3KDE9QEg1PzxCNj8BDAwMEA8QGBISGDEdGR0xPz8/Pz8xPzE/MTE/Pz8/MT80PzsxMTY/MTE/Njs6NTExPzQxMTQ0NDE0NDQxMTQxNP/AABEIAMgAyAMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAAFAAIDBAYBBwj/xAA7EAACAQIEAwUGBAUDBQAAAAABAgADEQQSITEFQVETImFxgQYyQpGhwVJysdEUIzPh8ENTkgcVFoLx/8QAGQEAAwEBAQAAAAAAAAAAAAAAAAECAwQF/8QAJBEAAgICAgEEAwEAAAAAAAAAAAECERIhAzFBBBNRYRQiMoH/2gAMAwEAAhEDEQA/ABOKTT0lDEJ3fQQziU0lCrT7vpOGLOxoZhqmZddxvJHEpIShuPXxljE4kImY6jlKrYiTAPkqWOzfrCszlHHU3UswZCp1K6/SEaWOp6EFmBFrkka+MbiyckEopXp4+mwDXIGoYfg00nadW+oIqLyYe96iFMLRPFEYrwARnAIrzt4ALLOhZy87eAWcInQkV5zNCgseIi0ZeNLQAkLRpeRlowtAVE150SBWl2gnONAx6rYWiIjjOGUIYYojFABlanpKLIMtjfyAuTrCGIrIo1I1210mfxvEbn+WxGwHjeYRi2aylQsSRdlS2UDUmx/wzmJcPSAUAMNb3g4MM4F9D8/K0lxjobEZQQNLGw8pvRllYOrV82hAz8mGl/Ocp1SFK8tx5yZMuml2BuSefQCMrqt9Lg6f3lEO+yE4gjnvvLWHxrK11a3rKrYW+uZAPzayIgDnKpMVtGywOK7Rblhmvz5ywahB1APiDeZfAVCAShX5y1TrvmDZrd7U3kYlZM0JMQMq4fEh1vpcGxttJs8zetF9olzRZpHmnMxisdEhaczSO8UYUPzTheNtFaSOhF4wsY7LHpR6x2AxATCtId0eUpBZbwx7tukIsVDzGmOInCssVEZijis5AKMRxDiJckAm19L7yrXxObU75QNBbaQMp3ANjzIjcplqKRk3ZItQ7+MWYnlp5yPKZKEMARKlNjYA29YbwHAO0AJ9TKGAoljttNhhCVAtYeAmc5NdG/HFPshpex9EjUsD5yLE+xi2OUk9Ieo4iXUqX0vJUn8luKXg8t4jwGpRJK3YQdTc31vfx5T1zF4XMDcX9Jl8f7P0y2dND8Qlx5a1Izlw2rQL4MzZToSCYXAnMPhQgsB5yULIlK3aCKpUMtFlkwWdyxDIMs7lk2WK0dARBI9aceAJ3NDFhZxUAjss5miLSlAmzhEmwo1I8JDqdt4Vw2FygA784OKQJ2NSkTLacLqMLhHI6hTC/BBRRi1QX07ulxeF8bx5ApFMa20J0t6RqqtsUm7pIw1Shl3ikuPrqMzsbDnFJstLR50cbT7q9mu+hvtKlRA2o08JSLaybPNaowscg1l2ggtY/wBpSB2PQywjn7RMpBLDvqBqATqIew9Sw3mfwg1uRC4rKguSo85lJWbw0gqlUS9hnB52mTqcYW9kVnPgJXr8WrHT3PAbxKLLlJG9r8SpUxld1B6EwXW4lT1NzbrbSYXEYgsLFtd735y92naJSZc/aEHPr3DbQW6HQy/bsy9xp0jTVVBGdSCDIwINZ6opqlMXLe7yN76iFnostswsSOt4saE5WyMCdtHBZ3LACMxWjiIrRgNijrRplIk4YojLGBwpqOFF7bsegjugofgQoOZrk/CAt4VSox92m5+kJYTAKLC0L4fBjpMZSbZa0jNhKx2RR5teRVMLXO7KPJZshhR0kNXDDpIsDA4vhNR/fZjblyimur4cRSrYf4fPYaSIZADLuAwz1HCIATzJ0AHjOqWjCO3SHIfKPNQLYkiEW4OgsDiaIbplYrfztKb8OemTmsxvuDcHykWmaYyXg7Sr1G0Q5RC1HBZ7NUOY215AwPRuD0MN4esLC+9pMtdGkEvIQw+GAFlCr1sLSPF8Ccm6qWv0io4sAwthuJWG8ytpmziqM9h+BVaZZmpgg8jqROYXBHN2YBDBrqDzBmuXiy271jB2MenU72U3BupDZGXyIlLkZm+NMkq0Oz7NAofLluCAVJJsT9YVxGG7RVdSQUUgoeQJvp6zOrjnpnPUZmQe4CBq3K5tCXC+NdppYKxBAPIwt9jULQ1FFyO8WG4Czppm1yp+c0/s7/DMGbEKodWAF72/v/eEeKY7CBGRERmIIBCZQD1vNIxtXZhJ1KjClJwiT1d5C0gojMjaPJjCY7GcAJNhqeU0/DcMKVO7b2u5g3hGF/1GH5f3hwC4I6i0lyvQJbHpxakBcZ2/KhMm/wC+ke5Sc/mIWDeG45ezNNgcyNlbTfoZJXr09nqKp6Fhp6CdcPSxlFNsjk5lBuOPRYq8brn3VpL53YwLiOOYpqmTOB3wNAFGo8p3EcTwqaGspPhrM7jMWHd3pioylrgqha3nNH6eCJh6mTf8pE+P4hUZmU1KmnVz3vTlFKFVKtQ/03vp3mIpk9L3MUXsx+DoXqZV2YviOEajVqUn3RyPPxhX2fpkrUy75Rfymv8AbP2dGIQ1qYHbIveH+4g+4mE4Fjuyqgn3Tow6ic0v2jow46UkHa+FBp8pQpVhqgOazWHjD9Sjmp1Ka2JKZqZ/GPD0mfq4UrqgYFeYXnMov5Oufyh1SncHqI2nWPOOpMxGZgb7MbaXnCoBvaWjOS8of2hEkTEnrICRHKIUK2W1xR6y1QxWovBypJKVREdDUF0zd4XtpE0ikwpjm7VGTkRdfMQLhsUaZsM2nXcTSPToYlLUm7FxtbVSfEftMrxDA1Kb2qb30I91/IxwroUlJOzb8Kx/aIFJ73IyarigLi+syKuaJpsCxpuoKMRbXmD4iaTBVqdXTNmYaE8zJksQcVLa7G1MV0BMgaq5Fwpt1tpCGIRKY1UEdY6hiALK2oPum2/gZOQKAHLVDHU6TnUk2hTEgi1mspPyjVylslu9blzhkDi/AbwjA00t+ASyjSngbhADcWMshpJILHBu3rVlyYh9QcqVhTQA63PreW8P7FuT/RpqOj1jUI9LD9YT4FUyYxNdHosvmVNx9LzZlgN7C87uKdRSMufcr+UYQ+xy0v5j1VRQVFqdG1rm3j1hip7KU2sDWxBFxcZhZh00AhzGXK2X3uXL6yB+I06VhWq0UNviqhb+k0ykzmvdAmp7I4QAkrUc5h71U6a+EU0iuGF1II5HkYpOTHX2eeq+k8k9p+G/wuJYAfy3Oan5Hl6T1DtIJ9ouHDFUGSw7RdaZ6Hp6zljKmdDRj+FcTCqEqAsnwkGzofAw7hsXhcrXqMSTu25mOwwtdTcEGxB5GWjTBEJQTZtGboMcR4xSFNqVFQcx1PSDGe4kAw4nWBEcYpA5NkivJVeU8072kKJyCKVRG4ghhaUTWtHDEiPEeSO08RUpHS5X9JoMHxWnUQU6irUU8jrM8cQvOVnfKboSPDlBxsS5MftHpNKph6tM06ip2drCwtb9vSZfH4SpgaoZD2lNv6bjUOOh8YOwnEmUWNwLQvwXieUuGbunkdr9ZGLV2WnGW0Noe0TscrKpU6GG6LhgaZJBsCh/QzD1TlqEjbNpNLwyp2qAg99dvLpFOKStDjK9MKcPrZy9KoBmGjHoORlHiwq0WV0YlkNrj41O0WJJZu44p1lFgfhcdDI85WmTU7xzd7xkr5LYb4HjGZA7vmzbi1skNZpgqfEOzB7MnUzT8CxhqUzmNyrW9IpRa2ZyrsKivkejU/BXW/5Tof1m/qMuzW1HM6TzjFJmpuOqm3nN3wSotXD0allLGktzbW9tfrN+CWmjHmVpM8/9q69cYutSqYjEhCoNFafukEaA2HpM3h+AYqqSaeHqkc2c5B46sZ7jWRdyPXnAfapmVQRYVBzA37p+s6oq9nDN4juG4tsPhqKYgjthSAIXvBgNAb+QikHGa7rURkZQoQrl0bUhiD4e6YoYjyRiRUmY9quL1EdKdJ2U5btkOpPIaf5rL2IqmpYAsq87C15z+EUrY9/xMx4+F9yN58y6RhatcsxZy2Ym5J94+cs4asT1P6zSV+Cc0a4/A/fQ+V9RBuJ4HUpuHogC/wABfUHwPOay47IjytDEswuDGOJJhyHYqw7OqNwRlD/3kr0b6c+hnNKLgzrhNSWuyg69JARLr0reEhZIJjcSuRGmTmkZImFYi4UnUADqY7JaZBh8I9Q5UBP2h/DezCgBqjsx6LoB6y/habIuUUwhtpY3v+8HLxbEM5WmXJDEEMgtobekjKUtLRo+OMactlrDeztNGNZ3PZICXU+855AeZgnD1AzGyKBfUAaamWcfxUutjmAA+H3c/j/nWVMMoyh8/eJuRHutiSin+pXxtPLUI5cpPw3Gmk1wdDuJzHpn7wOqrtbeU6esrtbJepWHOJVhUysp1jaNdihUm/W8FJUKmx2lyhVixpFqVsmUTRey9axdPxC48xM8VtrCHC3KOGHIyJ7Q6s2RMv8As7xSqlI0KdPOy1XA7x23206wcWvqJXwxqdrUp0wxLqGFjY6XB+hlelrNJ+THnv2pV4NTi8XjBTNR+xRQdVsGY620veNWo9QDLds63Atsd+Q84Ow2AuSa5amMtz/MUawZxni9TCLTaiUrHtCBlObKdxe3Xznrxgqa1Z4bm5NPdGpq03plXZQBkuT7wuCDvbpmimPp+0nEq9SktekqUS4D2p5LA6bk32JikLifyja/i6Aq+gj18zKyuOg+0lSobbE+B3EyNictbcnznXXMpysNR9eUrHFUxpfvdNzITi6Y3yofBv8ABACV8PTqAF1u45nRlPmJBiMIbA3OYb35yQYhL50qBjp3b2JkWKx7ixek2XfMFJt5jlFKKkqZUJSjK0UqqX0I1lNltCgqpV1VlN+RNmHlK2JpEeXLTeccuNxf0ehDljNfZTvLhqAKgB1DXMjw1HMb8hBmPrNTqEbCQlbLbpWa/BYoOuVjGIxF0Zkp02Zszk5S1zcj6zMYLHMTYEZraXNoSw3DsTVK0jUazG4NhkHrFjT2PPJdGzwnD6FakVFOmyMwuwA8NjB3HfY1GBqYTuPuULdx/LofpNNgcOKVOnTBuFQC/wCI9ZYzSFJroh72eR3amxp1Eam494MLGVwoUkD0nqHGeCUcWB2gIcDuuujr4eInlGLU03ZCbkMR8jabQkpCk6WyVyDOU62U+EptVM4r33mlEZGkwVQNp8oRwlOzW5QXwqk+W603IPPKbTRYKjaxIsZzzdHRDYcoHuL+USviavZ1KdS1wCVIva4Ij8M42+U5xNL02PMaj0kccqmmKUbuL8mg4Jw2nUpmoCLOCDma2l/7SrxLC9lVpqjBlYXNtQCusGUMOwRc2LpU0sCqiudjqdFvHkUkbOmJR7qQcwZQnUgtvPYckrd9nixg/wCa2jVUEFbCnMVzMT8PLoTFKXCuN0EpiilRWds2UkdxSRobnxtOTDM6MDy18aqiz2120ux8owVKlQXIFMDa2jkfaVcPSynMTd+Z/wA2l5Kmmuv2lk6RC+GuLAFRf1MhfhYtbOxvy3l4lep8o5cRlsALaephSC2BG4FWGqsoHi1jJKNLG09BnI/NeaANtpc9SY4Viuwub/hhjQZMCLjKyH+ZQJ6k09R6y9SxdKspRiUPK/wwkcblF3Hy1lOtUwznv2VhtbQwcdUwUqdoz/ETUpVAGzKoPdZTo6nc36iPxSCtTJaxqobNb4uYPqIYrYcFChJqUz5HJ+xgV0NCoFLXR0sreW3rIcEaLklZJ7NezLYvOTWFLJbTLmc357jSb7hHs/TwxD9pUqOFsCzDKPITIcGx/Y4hKmgRzlqgbWPxehHyBmz43UIotlazXW1ueu04+bJSo6uFqS0Fc0WaA8NxFgEDKbaAmE+28JhRq1RazTxLiwZa9VGJJWs4OviZ67i8eKdN6j6IiktYXM8m49jqdeu9WmhQNqwJ3bmfWdHAmmzHleiiHPWWMMl2HnKyC8v4GiWa2m06WrOfKnbNvwzEJkAeoLheoFpc/iqfJ1/5TNUwALb9dLCOFVdrr85n+Mn2zX8prpGpSopF1ZSfBryTEVGam9jrkNvlMsuU7EX8DrLGG4jUpmzHOnO+4i/GraYflZNWqL2GIZAcxHkLxlRczKtyE5krrvr9pHhHGU2IIvp1jqb97UXHL9pc+VYqPkftXyOUXplzCOrtlbSxtoABFKoNINcm6k6cysUzsTjsAKbchbxk6vcWuf0lVqyH4iY1qvSwnVZzUX7KLXIiNfWwAHkNZRQk3vJRYdPDWFiovpVIsR18yZMHLb5rQcKwG5P2j/4oke9lXptKsVBBwosGOp5X1lephqL6WF+dtT85VFcnQEHqf7yfI5AN7LzucoMA6Kv8P2bApUItvc3HykNcrUzKCCL3/I/IjwO0KFaZGq59PwnL8zKxwlHOGIWn1tV+xioaYJw1UZsrgkFgGHQWIP6mbLizhsNTcllF1zNf3OVzMpxij2dRXFmzjS2xbmfXeaPAN2mGqUFAZxRGXX33K5v1Mw5o5I34ZYuzuGDGxFYOOhE0CHQX3trMbgeIqWs1JUOS9xoNP/hmn4XXNSjTdr3K6336Tkxa7OyUk6onx+GFalUpk2DoRfp4zyLG4V6VR6bizK1j4+M9iWYX/qAlMVKTCwqFDn03F+6f1mvFLdGHItWZMS9wtznO3unfYSgoljDHK1+k6Uc72aamKbDvEn8x+0nWmNlIHgJn0p1W1s1jseQEuUq4p9xC1WodwpuFmiZm0Fcl9CAfOMan0J8txKow9d9aj9mPwgZjGvgXGq13vb4hcR2Ki3TdkI5euhhHDtztp+szlDGVEfs6w32P3BnonAODl6XbsLopAUddN/ScvPG6aOr08qtMB4vC06YOlxn0suY339N4oRxeHzubllAbkdDoNIpMVoUns8zSoZYp1D4SkJaoUXf3VY+NtJurIaRbFU9Z0PzJMYMKE0eooY/Cvff6SwAtMAsqoOr95/Rf3jIZzDuzN/Lps2u9pfc06YvWVAbbFszQRieNkDJSzAcydz+0G5mc3Ylj4mGSQ8Gws/E7sRRRaa/iMI8N4dVrEEFmF9Xfb/1WUOH4amlnrMAOQhpfbCjTGWnTJtzicmUopDOIYNkcg53A01Oh9BI17NlyhVRvLeS/+TYeqblmptzut1M6zUqvuvTJ5FWGvpFdjqgLxFDlykWZT3bc46jj3p58hIIA73JLC1/kBL2IoNbK+491oPogKzZlKogvY/6j/D6Df0jAN8N4ccVTp06mRAguf9xr8ieumvnNQiBQFUBVAsABa1tJhcLiazLdGFGmCe9vUqHrDOA4t2aFS6lV1ZmOuvU/OZThl0aRlRo6R7xU+Y+8wPt7iQ2JVAQQlMbdTr+01icaoVD3KgZQbXCkA/OeZY/EmpUdza5Y/rM+OMlK2i+SUcdMiRrSzRQMdDbrfkJUEs4ZwoJIDa2IvuJ0o52X2xNSr3EOSmo7xOwHUxo4j2YyUFsPici7uZWxGLL2pouVL6KOZhvh9I01F0VbjQ2uzxrZD0U6XEsUdMhcfkhLCVamhqoijpzkz1WIsu/lB9XAVnNywWVtE2mWsX2d1WorAZro24E9B4Q5FCmqVHylNg7BfpPOKOFqLo7ionNT9po+Ecc/hqaILkF7KTqqA8jzmPNFtWjTikk6CuLqCnWKsHK6H3SbjnqYpFxp6lQpVQAPlAOTmLnX6xQhBNdi5JyTqjIMcU+ppUKI6soW33lTE1Ka/wBSs9Y/hTuJ84opqwRVfihXSjTSmOoF3+Zg52LEliSfOKKSaKKOosnSpb3RrOxSBki4d6huxlpOEqeYiigA4+zzHUWMr4jgNanqFbzEUUaERpxHEUtGJdejDMJLXx9OsBvTcHYnuP6xRQA6tR2YIFZnt3UGwHUnp5fSdr4VVsKjio/4VP8ALT9zFFGiWRYnFkCy6ADlygkxRRsUTojgdDFFAovcEo3qZyO6ouSdhNImIp1DlVSfHa0UUpdGUuyWqmT3Eubb6yqalc7Kv/KKKUSVqmCrtctUVB0BvIMKhRv6qt1B2InYomNBbgmKqjGdk1R3pNTbICdBpf7ERRRTCSVmyP/Z" />
        </div>
      </header>

      <form className="flex flex-col  items-center mt-44 flex-grow ">
        <Image
          src="https://www.google.co.uk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
          height={100}
          width={300}
        />

        <div className="flex w-full w-4/5 mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-5 mr-3 text-gray-500" />
          <input ref={searchInputRef} type="text" className="flex-grow focus:outline-none " />
          <MicrophoneIcon className="h-5" />
        </div>
        <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4">
          <button onClick={search} className="btn">Google Search</button>
          <button className="btn">I'm Feeling Lucky</button>
        </div>
      </form>

      <Footer />
    </div>
  );
}
